### ISSUE TITLE
Generated reports are not CI-friendly

### ISSUE THREAD

**Issue by kibertoad** [a11smiles/karma-html-detailed-reporter#1]
When report HTML is opened not from within the project directory, formatting goes bananas due to being unable to access bootstrap.css, jquery.js and bootstrap.js (since e. g. TeamCity stores report artefacts separately from project workspace)

Would it be possible to add an optional mode which would either reference resources that are available online, or bundle them inside the reports output directory alongside report itself?

**Comment by a11smiles** [comment]
great thought.  will do.

**Comment by kibertoad** [comment]
Woah, now that was a quick fix, thank you!
Any ETA on when the new version hits npmjs?
