### ISSUE TITLE
useHostedBootstrap doesn't seem to work properly

### ISSUE THREAD

**Issue by kibertoad** [a11smiles/karma-html-detailed-reporter#2]
I get following errors when I try to use the new option:

Failed to load resource: net::ERR_FILE_NOT_FOUND
file://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file://code.jquery.com/jquery.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
html-results.html:37 Uncaught ReferenceError: $ is not defined

probably "http://" should be there in place of "file://".

**Comment by a11smiles** [comment]
looks like the browser is interpreting the relative url incorrectly.

**Comment by a11smiles** [comment]
fixed in version 1.1.11

**Comment by kibertoad** [comment]
Tested the fix, it worked, thank you again!
