### ISSUE TITLE
Disable automatic refresh/change refresh time

### ISSUE THREAD

**Issue by freeranger** [a11smiles/karma-html-detailed-reporter#4]
Hi,

We run CI builds with Team City and display the output of your reporter in an iframe in Team City,
By default the refresh is every second so the iframe flashes horribly as it refreshes...indeed it feels like more than every second as I guess it takes some time for the frame to reload, by which time it wants to do another refresh and the cycle continues - it essentially reloads more or less immediately after the initial display.

It would be great to have two options (or possibly a single combined option)
1. disable the refresh completely (maybe set refresh interval to 0?) by default
2. set it to a specific default value.

These could be either config values supplied to the reporter setup or even query params that can be supplied at runtime.

thanks

**Comment by kibertoad** [comment]
We are using Team City as well and have encountered the same issue.

**Comment by a11smiles** [comment]
@freeranger great insight.  I originally designed the tool to allow you to "watch" tests while developing/debugging locally.  I see a lot of people are now using the tool for Team City, which is cool, but of course, could require some additional functionality.

I will get this done over the next two weeks for you.  Thanks for the request and if there's any other recommendations you have, let me know.

**Comment by a11smiles** [comment]
two new options have been added `autoRefresh` (default: _true_) and `refreshTimeout` (default: _1000_) to enable/disable refreshing and the refresh timeout, respectively.

**Comment by freeranger** [comment]
@a11smiles Great, thanks for that - m8.
A couple of tiny bug-ettes with it though, the UI now shows this:

![image](https://cloud.githubusercontent.com/assets/1401069/21003944/f3e3941e-bd25-11e6-828c-13528de5e6cf.png)

When I turn off refresh - ideally of course it wouldn't show the {{DateTime_Stamp}} and the button would be "Enable Refresh", or perhaps not visible at all since I have programmatically disabled refresh

thanks again for the quick response.
