### ISSUE TITLE
UI bugs when autoRefresh is disabled in code

### ISSUE THREAD

**Issue by freeranger** [a11smiles/karma-html-detailed-reporter#5]
Following on from #4, the fix for this has introduced a couple of bug-ettes.
I mentioned them in that issue but of course it is closed now, so raising an new one.

When I have programmatically disabled autoRefresh, I see this in the UI:
![image](https://cloud.githubusercontent.com/assets/1401069/21003944/f3e3941e-bd25-11e6-828c-13528de5e6cf.png)

- it should not show {{DateTime_Stamp}}
- The button should show "Enable Refresh", or perhaps not visible at all since I have programmatically disabled refresh.  Currently the button doesn't actually work in this state

**Comment by a11smiles** [comment]
In code changes, I accidentally deleted a line which is causing the issue. I am creating a fix now.
