### ISSUE TITLE
shouldReload is not a function when auto refresh is disabled in code

### ISSUE THREAD

**Issue by freeranger** [a11smiles/karma-html-detailed-reporter#7]
Following on from https://github.com/a11smiles/karma-html-detailed-reporter/issues/5

This is what I now see in the UI when auto refresh has been disabled programmatically:
![image](https://cloud.githubusercontent.com/assets/1401069/21762854/d6e82442-d652-11e6-8064-bb03998269d2.png)

I'm not sure what the timestamp represents (the time is 10:04 GMT on 9 Jan 2017at the time of the screenshot) and the button says "Disable" when it is already disabled - so it should say "Enable" to allow me to toggle it on/off

Also, there is an error in the console about shouldReload not being a function - this is your code:
```javascript
            var reload = shouldReload();

            var shouldReload = function() {
                if (location.search != null && location.search != undefined && location.search.length > 0)
                    return location.search.substr(1) === 'true' ? true : false;
                else
                    return true;
            };
```
The error is on the first line, presumably because you are referencing the function before it is defined.

**Comment by a11smiles** [comment]
closed with #8
